// generator.ts — Generates a standalone MCP server ZIP from a ToolsFile.
// The generated server reads credentials from .env, supports all HTTP methods,
// and has no dependency on Helios's backend or MongoDB.

import JSZip from "jszip"
import type { ToolsFile, ToolAuthEnrichment } from "./generate_tool_registry.ts"

// ─── Env Var Names ─────────────────────────────────────────────────────────────

/**
 * Maps an auth enrichment to the env var name(s) the generated server will use.
 * These become the keys in .env.example and the process.env lookups in server.ts.
 */
function getEnvVars(auth: ToolAuthEnrichment | null): Record<string, string> {
  if (!auth) return {}
  switch (auth.template) {
    case "bearer_token":
      return { BEARER_TOKEN: "your_bearer_token_here" }
    case "api_key_header":
      return { API_KEY: "your_api_key_here" }
    case "api_key_query":
      return { API_KEY: "your_api_key_here" }
    case "oauth2_client_creds":
      return {
        CLIENT_ID: "your_client_id_here",
        CLIENT_SECRET: "your_client_secret_here",
      }
    case "oauth2_auth_code":
      return { ACCESS_TOKEN: "your_access_token_here" }
    case "basic_auth":
      return { API_CREDENTIALS: "username:password" }
    default:
      return {}
  }
}

// ─── Auth Injection Code ────────────────────────────────────────────────────────

/**
 * Returns the inline TypeScript snippet that injects auth into headers/params
 * for the generated server. Reads from process.env instead of MongoDB.
 */
function getAuthInjectionCode(auth: ToolAuthEnrichment | null): string {
  if (!auth) return ""
  switch (auth.template) {
    case "bearer_token":
      return `
      const token = process.env.BEARER_TOKEN
      if (token) headers["Authorization"] = \`Bearer \${token}\``

    case "api_key_header":
      return `
      const apiKey = process.env.API_KEY
      if (apiKey) headers["${auth.header_name || "X-API-Key"}"] = apiKey`

    case "api_key_query":
      return `
      const apiKey = process.env.API_KEY
      if (apiKey) params.set("${auth.param_name || "api_key"}", apiKey)`

    case "oauth2_client_creds":
      return `
      const token = process.env.ACCESS_TOKEN
      if (token) headers["Authorization"] = \`Bearer \${token}\``

    case "oauth2_auth_code":
      return `
      const token = process.env.ACCESS_TOKEN
      if (token) headers["Authorization"] = \`Bearer \${token}\``

    case "basic_auth":
      return `
      const creds = process.env.API_CREDENTIALS
      if (creds) headers["Authorization"] = \`Basic \${Buffer.from(creds).toString("base64")}\``

    default:
      return ""
  }
}

// ─── Generated server.ts ───────────────────────────────────────────────────────

function generateServerTs(registry: ToolsFile): string {
  const firstAuth = registry.tools.find(t => t.enrichment?.auth)?.enrichment?.auth ?? null
  const authInjection = getAuthInjectionCode(firstAuth)

  return `// Generated by Helios — do not edit manually.
// Start: npx tsx server.ts
import "dotenv/config"
import { readFileSync } from "fs"
import { randomUUID } from "node:crypto"
import express from "express"
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js"
import { StreamableHTTPServerTransport } from "@modelcontextprotocol/sdk/server/streamableHttp.js"
import { isInitializeRequest } from "@modelcontextprotocol/sdk/types.js"
import { z } from "zod"

const toolsFile = JSON.parse(readFileSync("tools.json", "utf8"))
const BASE_URL = toolsFile.baseUrl

function registerTool(server, endpoint) {
  const schema = {}
  const required = Array.isArray(endpoint.input_schema.required) ? endpoint.input_schema.required : []

  for (const paramName in endpoint.input_schema.properties) {
    const p = endpoint.input_schema.properties[paramName]
    const isRequired = required.includes(paramName)
    let field
    if (p.type === "number" || p.type === "integer") {
      field = z.number().describe(p.description || "")
    } else if (p.type === "boolean") {
      field = z.boolean().describe(p.description || "")
    } else if (p.type === "object") {
      field = z.record(z.string(), z.any()).describe(p.description || "")
    } else if (p.type === "array") {
      const items = p.items
      if (items?.type === "object") field = z.array(z.record(z.string(), z.any())).describe(p.description || "")
      else if (items?.type === "number" || items?.type === "integer") field = z.array(z.number()).describe(p.description || "")
      else field = z.array(z.string()).describe(p.description || "")
    } else if (Array.isArray(p.enum) && p.enum.length > 0) {
      const [first, ...rest] = p.enum
      field = z.enum([first, ...rest]).describe(p.description || "")
    } else {
      field = z.string().describe(p.description || "")
    }
    schema[paramName] = isRequired ? field : field.optional()
  }

  server.registerTool(
    endpoint.name,
    { description: endpoint.description, inputSchema: Object.keys(schema).length > 0 ? schema : undefined },
    async (args) => {
      // ── Path params ──────────────────────────────────────────────────────────
      let url = BASE_URL + endpoint.handler.path
      for (const paramName in endpoint.input_schema.properties) {
        if (endpoint.handler.path.includes(\`{\${paramName}}\`) && args[paramName] !== undefined) {
          url = url.replace(\`{\${paramName}}\`, String(args[paramName]))
        }
      }

      // ── Query params ─────────────────────────────────────────────────────────
      const params = new URLSearchParams()
      for (const paramName of (endpoint.handler.query_params || [])) {
        const val = args[paramName]
        if (val !== undefined && val !== null && String(val).trim() !== "") {
          params.append(paramName, String(val))
        }
      }

      // ── Fixed query params ───────────────────────────────────────────────────
      for (const [k, v] of Object.entries(endpoint.handler.fixed_query_params || {})) {
        params.set(k, v)
      }

      // ── Headers ──────────────────────────────────────────────────────────────
      const headers = { ...(endpoint.handler.headers || {}) }

      // ── Auth injection from .env ──────────────────────────────────────────────${authInjection}

      // ── Finalize URL ─────────────────────────────────────────────────────────
      if (params.toString()) url += "?" + params.toString()

      const method = endpoint.handler.method.toUpperCase()

      // ── Build request body for non-GET methods ────────────────────────────────
      let body = undefined
      if (method !== "GET" && method !== "HEAD") {
        const qp = endpoint.handler.query_params || []
        const bodyParams = {}
        for (const key in args) {
          if (!endpoint.handler.path.includes(\`{\${key}}\`) && !qp.includes(key) && args[key] !== undefined) {
            bodyParams[key] = args[key]
          }
        }
        if (Object.keys(bodyParams).length > 0) {
          headers["Content-Type"] = "application/json"
          body = JSON.stringify(bodyParams)
        }
      }

      // ── Execute request ───────────────────────────────────────────────────────
      const controller = new AbortController()
      const timer = setTimeout(() => controller.abort(), 10_000)
      let response
      try {
        response = await fetch(url, { method, headers, body, signal: controller.signal })
      } catch (err) {
        clearTimeout(timer)
        const msg = err.name === "AbortError"
          ? \`Request timed out after 10 seconds\`
          : \`Network error: \${err.message}\`
        return { content: [{ type: "text", text: msg }] }
      }
      clearTimeout(timer)

      const text = await response.text()
      if (!response.ok) {
        const reason = response.status === 401
          ? \`Unauthorized (401) — check your credentials in .env\`
          : response.status === 429
          ? \`Rate limit hit (429) — wait and retry\`
          : \`API error \${response.status}: \${text.slice(0, 500)}\`
        return { content: [{ type: "text", text: reason }] }
      }

      let data
      try { data = text ? JSON.parse(text) : "Success (empty response)" }
      catch { data = text }
      return { content: [{ type: "text", text: typeof data === "string" ? data : JSON.stringify(data) }] }
    }
  )
}

// ─── Express + MCP Session Management ─────────────────────────────────────────

const app = express()
app.use(express.json({ limit: "10mb" }))

const transports = new Map()
const servers = new Map()
const timers = new Map()
const SESSION_TTL = 30 * 60 * 1000

function refreshTimer(sessionId) {
  const existing = timers.get(sessionId)
  if (existing) clearTimeout(existing)
  timers.set(sessionId, setTimeout(() => {
    transports.delete(sessionId)
    servers.delete(sessionId)
    timers.delete(sessionId)
  }, SESSION_TTL))
}

app.post("/mcp", async (req, res) => {
  const sessionId = req.headers["mcp-session-id"]

  if (sessionId && transports.has(sessionId)) {
    refreshTimer(sessionId)
    await transports.get(sessionId).handleRequest(req, res, req.body)
    return
  }

  if (!sessionId && isInitializeRequest(req.body)) {
    const server = new McpServer({ name: "helios-generated-server", version: "1.0.0" })
    const transport = new StreamableHTTPServerTransport({
      sessionIdGenerator: () => randomUUID(),
      onsessioninitialized: (id) => {
        transports.set(id, transport)
        servers.set(id, server)
        refreshTimer(id)
      }
    })
    transport.onclose = () => {
      if (transport.sessionId) {
        transports.delete(transport.sessionId)
        servers.delete(transport.sessionId)
        const t = timers.get(transport.sessionId)
        if (t) { clearTimeout(t); timers.delete(transport.sessionId) }
      }
    }
    for (const tool of toolsFile.tools) registerTool(server, tool)
    await server.connect(transport)
    await transport.handleRequest(req, res, req.body)
    return
  }

  res.status(400).json({ jsonrpc: "2.0", error: { code: -32000, message: "Invalid request" }, id: null })
})

app.get("/mcp", async (req, res) => {
  const sessionId = req.headers["mcp-session-id"]
  if (!sessionId || !transports.has(sessionId)) { res.status(400).send("Invalid session"); return }
  await transports.get(sessionId).handleRequest(req, res)
})

app.delete("/mcp", async (req, res) => {
  const sessionId = req.headers["mcp-session-id"]
  if (!sessionId || !transports.has(sessionId)) { res.status(400).send("Invalid session"); return }
  await transports.get(sessionId).handleRequest(req, res)
})

const PORT = process.env.PORT || 3333
app.listen(PORT, () => console.log(\`MCP server running on port \${PORT}\`))
`
}

// ─── Generated package.json ────────────────────────────────────────────────────

function generatePackageJson(specName: string): string {
  return JSON.stringify({
    name: specName.toLowerCase().replace(/[^a-z0-9-]/g, "-") + "-mcp-server",
    version: "1.0.0",
    type: "module",
    scripts: {
      start: "npx tsx server.ts"
    },
    dependencies: {
      "@modelcontextprotocol/sdk": "^1.27.1",
      "dotenv": "^16.6.1",
      "express": "^5.2.1",
      "zod": "^4.3.6"
    },
    devDependencies: {
      "@types/node": "^22.0.0",
      "tsx": "^4.0.0",
      "typescript": "^5.0.0"
    }
  }, null, 2)
}

// ─── Generated .env.example ────────────────────────────────────────────────────

function generateEnvExample(registry: ToolsFile): string {
  const firstAuth = registry.tools.find(t => t.enrichment?.auth)?.enrichment?.auth ?? null
  const envVars = getEnvVars(firstAuth)

  if (Object.keys(envVars).length === 0) {
    return "# This API requires no authentication\n"
  }

  const lines = ["# Fill in your credentials below, then rename this file to .env", ""]
  for (const [key, placeholder] of Object.entries(envVars)) {
    lines.push(`${key}=${placeholder}`)
  }
  lines.push("")
  lines.push("# Optional: change the port the MCP server runs on")
  lines.push("# PORT=3000")

  return lines.join("\n")
}

// ─── Generated README.md ───────────────────────────────────────────────────────

function generateReadme(specName: string, registry: ToolsFile): string {
  const firstAuth = registry.tools.find(t => t.enrichment?.auth)?.enrichment?.auth ?? null
  const envVars = getEnvVars(firstAuth)
  const toolCount = registry.tools.length
  const safeName = specName.toLowerCase().replace(/[^a-z0-9-]/g, "-")

  const credSteps = Object.keys(envVars).length > 0
    ? `3. Copy \`.env.example\` to \`.env\` and fill in your credentials:
\`\`\`bash
cp .env.example .env
\`\`\`
Then open \`.env\` and replace the placeholder values:
\`\`\`
${Object.keys(envVars).map(k => `${k}=your_value`).join("\n")}
\`\`\``
    : `3. No credentials needed — this API is public. Skip this step.`

  return `# ${specName} MCP Server

Generated by [Helios](https://github.com/acm-projects/Helios) — ${toolCount} tools available.

## Prerequisites

- Node.js 18 or later
- npm

## Setup

1. Unzip this folder and open a terminal inside it.

2. Install dependencies:
\`\`\`bash
npm install
\`\`\`

${credSteps}

4. Start the server:
\`\`\`bash
npm start
\`\`\`

You should see: \`MCP server running on port 3000\`

5. Verify it's working:
\`\`\`bash
curl -X POST http://localhost:3333/mcp \\
  -H "Content-Type: application/json" \\
  -d '{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2024-11-05","capabilities":{},"clientInfo":{"name":"test","version":"1.0.0"}}}'
\`\`\`
You should get a JSON response with \`"result"\` — the server is ready.

---

## Connecting to Claude Desktop

**Find your config file:**
- Windows: \`C:\\Users\\<you>\\AppData\\Roaming\\Claude\\claude_desktop_config.json\`
- Mac: \`~/Library/Application Support/Claude/claude_desktop_config.json\`

**Add this block** (replace the path with the actual folder location):

Windows:
\`\`\`json
{
  "mcpServers": {
    "${safeName}": {
      "command": "cmd",
      "args": ["/c", "npx", "tsx", "C:\\\\full\\\\path\\\\to\\\\${specName}\\\\server.ts"]
    }
  }
}
\`\`\`

Mac/Linux:
\`\`\`json
{
  "mcpServers": {
    "${safeName}": {
      "command": "npx",
      "args": ["tsx", "/full/path/to/${specName}/server.ts"]
    }
  }
}
\`\`\`

Then **fully restart Claude Desktop** (quit from the tray, reopen). The tools will appear in the tools menu.

---

## Connecting to Cursor

Open Cursor Settings → MCP → Add Server:
\`\`\`json
{
  "${safeName}": {
    "command": "npx",
    "args": ["tsx", "C:/full/path/to/${specName}/server.ts"]
  }
}
\`\`\`

---

## Connecting to any MCP-compatible agent

This server implements the standard [Model Context Protocol](https://modelcontextprotocol.io).
Any MCP client can connect to it at:
\`\`\`
http://localhost:3333/mcp
\`\`\`

---

## Available Tools (${toolCount})

${registry.tools.map(t => `- **${t.name}** — ${t.description || "no description"}`).join("\n")}
`
}

// ─── Main Export ───────────────────────────────────────────────────────────────

/**
 * Generates a complete MCP server ZIP from a ToolsFile.
 * Returns a Buffer ready to be streamed as a file download.
 */
export async function generateServerZip(specName: string, registry: ToolsFile): Promise<Buffer> {
  const zip = new JSZip()
  const folder = zip.folder(specName)!

  folder.file("server.ts", generateServerTs(registry))
  folder.file("package.json", generatePackageJson(specName))
  folder.file("tools.json", JSON.stringify(registry, null, 2))
  folder.file(".env.example", generateEnvExample(registry))
  folder.file("README.md", generateReadme(specName, registry))
  folder.file("tsconfig.json", JSON.stringify({
    compilerOptions: {
      target: "ES2020",
      module: "ESNext",
      moduleResolution: "bundler",
      types: ["node"],
      strict: false,
      skipLibCheck: true
    }
  }, null, 2))

  return zip.generateAsync({ type: "nodebuffer", compression: "DEFLATE" })
}
